spring:
  application:
    name: otus-ui

server:
  port: 8080
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://18.220.162.231:8761/eureka/
  instance:
    preferIpAddress: true

management:
  security:
    enabled: false