spring:
  application:
    name: otus-ui

server:
  port: 8080
  
eureka:
  client:
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://34.193.236.46:8761/eureka/
  instance:
    preferIpAddress: true
