spring:
  application:
    name: otus-ui

server:
  port: 8080
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://34.193.236.46:8761/eureka/
  instance:
    preferIpAddress: true

management:
  security:
    enabled: false