server:
  port: 8761

eureka:
  instance:
    hostname: 34.193.236.46
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://34.193.236.46:${server.port}/eureka/

spring.cloud.config.discovery.enabled: true