server:
  port: 8761

eureka:
  instance:
    hostname: 18.220.162.231
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://18.220.162.231:${server.port}/eureka/

spring.cloud.config.discovery.enabled: true